# yaml-language-server: $schema=../../schema/local.json
config:
  logging:
    format: json
    #    filter: 'response.code != 500'
    fields:
      add:
        backend: backend
binds:
- port: 3000
  listeners:
  - routes:
    - policies:
        # Mark this route as a2a traffic
        a2a: {}
      backends:
      - host: localhost:9999