binds:
- port: 8080
  listeners:
  - name: http
    protocol: HTTP
    routes:
    - backends:
      - host: datadog.example.com:443
        policies:
          backendAuth:
            headers:
              - name: dd-api-key
                value: primary-api-key
              - name: dd-application-key
                value: application-key
              - name: x-auth-token
                prefix: "Bearer "
                value: token-value
    - backends:
      - host: combined.example.com:443
        policies:
          backendAuth:
            key:
              value: primary-creds
            headers:
              - name: x-auth-email
                value: user@example.com
