[package]
name = "agentgateway"
version = "0.4.12"
edition = "2024"
rust-version = "1.85"

[workspace]
resolver = "2"
members = [
  "a2a-sdk",
  "agent-core",
  "agent-xds",
  "agent-hbone",
  "agent-proxy",
]

[workspace.dependencies]
a2a-sdk = { version = "0.4.0", path = "a2a-sdk" }
agent-core = { path = "agent-core" }
agent-hbone = { path = "agent-hbone" }
anyhow = "1.0"
arcstr = "1.2"
async-stream = "0.3.6"
async-trait = "0.1"
aws-config = "1.6.1"
aws-sdk-lambda = "1.67.0"
aws-smithy-runtime-api = "1.7.4"
axum = "0.8"
axum-core = "0.5.2"
axum-extra = "0.10"
backoff = "0.4"
base64 = "0.22"
byteorder = "1.5"
bytes = "1.10.1"
chrono = "0.4.40"
clap = "4.5"
criterion = "0.5"
ctor = "0.3"
diff = "0.1"
duration-str = "0.13"
educe = "0.6.0"
enum_delegate = "0.2.0"
enum_dispatch = "0.3.13"
eventsource-stream = "0.2.3"
flurry = "0.5.2"
futures = "0.3.31"
futures-core = "0.3"
futures-util = "0.3.31"
google-cloud-auth = "0.18.0"
h2 = "0.4.9"
hashbrown = "0.15"
headers = "0.4"
hex = "0.4.3"
hickory-client = "0.24"
hickory-proto = "0.24"
hickory-resolver = "0.24"
hickory-server = "0.24"
homedir = "0.3.4"
http = "1.3.1"
http-body = "1"
http-body-util = "0.1.3"
hyper = "1.5"
hyper-rustls = { version = "0.27.0", default-features = false }
hyper-util = "0.1"
include_dir = "0.7.4"
ipnet = "2.9"
jemalloc_pprof = "0.6.0"
jsonwebtoken = "9.3"
keyed_priority_queue = "0.4"
lazy_static = "1.4"
libc = "0.2"
local-ip-address = "0.6"
log = "0.4"
matches = "0.1"
mime = "0.3.17"
minijinja = "2.9.0"
nix = "0.29"
oid-registry = "0.8"
once_cell = "1.21.3"
openapiv3 = "2.0.0"
opentelemetry = "0.29"
opentelemetry-http = "0.29"
opentelemetry-otlp = "0.29"
opentelemetry_sdk = "0.29"
pbjson = "0.7"
pbjson-build = "0.7"
pbjson-types = "0.7"
pin-project-lite = "0.2.16"
pingora-pool = "0.4.0"
ppp = "2.3.0"
prometheus-client = "0.23.1"
prometheus-parse = "0.2"
prost = "0.13.5"
prost-build = "0.13"
prost-types = "0.13.5"
prost-wkt = "0.6.0"
rcgen = "0.13"
regex = "1.11.1"
reqwest = { version = "0.12.14", default-features = false }
ring = "0.17"
rmcp = { git = "https://github.com/modelcontextprotocol/rust-sdk", rev = "6a423048fa7f3da99190f28bcb2d6d8cdbb99bbe" }
rustc_version = "0.4"
rustls = { version = "0.23.26", default-features = false }
rustls-native-certs = "0.8"
rustls-pemfile = "2.2"
secrecy = "0.10.3"
serde = "1.0.219"
serde_json = "1.0.140"
serde_path_to_error = "0.1.17"
serde_regex = "1.1.0"
serde_yaml = "0.9.34"
socket2 = "0.5"
split-iter = "0.1.0"
sse-stream = "0.1.3"
sync_wrapper = "1.0.2"
test-case = "3.3"
textnonce = "1.0"
thiserror = "2.0.12"
tikv-jemallocator = "0.6.0"
tls-listener = "0.11"
tokio = "1.44.2"
tokio-rustls = { version = "0.26.2", default-features = false }
tokio-stream = "0.1"
tokio-util = "0.7"
tonic = { version = "0.12.0", default-features = false }
tonic-build = { version = "0.12", default-features = false }
tower = "0.5"
tower-http = "0.5"
tower-serve-static = "0.1.1"
tracing = "0.1.41"
tracing-appender = "0.2"
tracing-core = "0.1"
tracing-log = "0.2"
tracing-subscriber = "0.3"
url = "2.5"
wiremock = "0.6.3"
x509-parser = { version = "0.17", default-features = false }
itertools = "0.14"
rand = "0.9"

[features]
default = []
gcp = ["dep:google-cloud-auth"]
aws = ["dep:aws-config", "dep:aws-sdk-lambda", "dep:aws-smithy-runtime-api"]
ui = ["dep:include_dir", "dep:tower-serve-static"]

[dependencies]
arcstr = { workspace = true, features = ["serde"] }
async-stream = { workspace = true }
rmcp = { workspace = true, features = ["client", "transport-sse", "transport-child-process"] }
sse-stream = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-rustls = { workspace = true }
rustls = { workspace = true, features = ["ring"] }
tls-listener = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
rand = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
axum = { workspace = true, features = ["macros"] }
axum-extra = { workspace = true, features = ["json-lines", "typed-header"] }
tower-http = { workspace = true, features = ["cors"] }
headers = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true, features = ["codec"] }
http = { workspace = true }
base64 = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
tonic = { workspace = true, features = ["prost", "codegen", "transport"] }
split-iter = { workspace = true }
thiserror = { workspace = true }
prometheus-client = { workspace = true }
serde_yaml = { workspace = true }
ppp = { workspace = true }
bytes = { workspace = true }
jsonwebtoken = { workspace = true }
openapiv3 = { workspace = true }
reqwest =  { workspace = true, features = ["http2", "charset", "macos-system-configuration", "rustls-tls"] }
itertools = { workspace = true }
async-trait = { workspace = true }
lazy_static = { workspace = true }

pbjson = { workspace = true }
pbjson-types = { workspace = true }

opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }
opentelemetry-http = { workspace = true }
opentelemetry-otlp = { workspace = true, features = ["grpc-tonic"] }

secrecy = { workspace = true }

google-cloud-auth = { workspace = true, optional = true }
aws-config = { workspace = true, optional = true }
aws-sdk-lambda = { workspace = true, optional = true }
aws-smithy-runtime-api = { workspace = true, optional = true }
pin-project-lite = { workspace = true }
futures-util = { workspace = true }
a2a-sdk = { workspace = true }
eventsource-stream = { workspace = true }
http-body-util = { workspace = true }
mime = { workspace = true }
homedir = { workspace = true }

include_dir = { workspace = true, optional = true }
tower-serve-static = { workspace = true, optional = true }
regex = { workspace = true }
once_cell = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true, features = ["prost", "transport"] }
prost-build = { workspace = true }
anyhow = { workspace = true }
rustc_version = { workspace = true }
pbjson-build = { workspace = true }

[lib]
path = "src/lib.rs"
bench = false

[[bin]]
name = "agentgateway"
path = "src/main.rs"
bench = false

[dev-dependencies]
serde_json = { workspace = true }
tokio = { workspace = true }
wiremock = { workspace = true }
