[package]
name = "agentproxy"
version = "0.4.8"
edition = "2024"
rust-version = "1.85"

[workspace]
resolver = "2"
members = [
  "a2a-sdk"
]

[features]
default = []
gcp = ["dep:google-cloud-auth"]
aws = ["dep:aws-config", "dep:aws-sdk-lambda", "dep:aws-smithy-runtime-api"]
ui = ["dep:include_dir", "dep:tower-serve-static"]

[dependencies]
arcstr = { version = "1.2", features = ["serde"] }
async-stream = "0.3"
rmcp = { git = "https://github.com/modelcontextprotocol/rust-sdk", features = [
  "client",
  "transport-sse",
  "transport-child-process",
], rev="6a423048fa7f3da99190f28bcb2d6d8cdbb99bbe" }
sse-stream = "0.1.3"
tokio = { version = "1.42", features = ["full"] }
tokio-rustls = "0.26"
rustls = {version = "0.23", features = ["ring"]}
tls-listener = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rand = "0.8"
futures = "0.3"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
axum = { version = "0.8", features = ["macros"] }
axum-extra = { version = "0.10", features = ["json-lines", "typed-header"] }
tower-http = { version = "0.5", features = ["cors"] }
headers = "0.4"
tokio-stream = { version = "0.1" }
tokio-util = { version = "0.7", features = ["codec"] }
http = "1.3"
base64 = "0.22"
prost = "0.13"
prost-types = "0.13"
tonic = { version = "0.12", default-features = false, features = [
  "prost",
  "codegen",
  "transport"
] }
split-iter = "0.1"
thiserror = "2.0"
prometheus-client = { version = "0.23" }
serde_yaml = "0.9.34"
ppp = "2.3.0"
bytes = "1.10.1"
jsonwebtoken = "9.3"
openapiv3 = "2.0.0"
reqwest = "0.12.14"
itertools = "0.14"
async-trait = "0.1"
lazy_static = "1.4"

pbjson = "0.7"
pbjson-types = "0.7"

opentelemetry = { version = "0.29" }
opentelemetry_sdk = { version = "0.29" }
opentelemetry-http = { version = "0.29" }
opentelemetry-otlp = { version = "0.29", features = ["grpc-tonic"]  }

secrecy = "0.10.3"

google-cloud-auth = {version = "0.18.0", optional = true}
aws-config = {version = "1.6.1", optional = true}
aws-sdk-lambda = {version = "1.67.0", optional = true}
aws-smithy-runtime-api = {version = "1.7.4", optional = true}
pin-project-lite = "0.2.16"
futures-util = "0.3.31"
a2a-sdk = { version = "0.4.0", path = "a2a-sdk" }
eventsource-stream = "0.2.3"
http-body-util = "0.1.3"
mime = "0.3.17"
homedir = "0.3.4"

include_dir = { version = "0.7.4", optional = true }
tower-serve-static = { version = "0.1.1", optional = true }
regex = "1.11.1"
once_cell = "1.21.3"

[build-dependencies]
tonic-build = { version = "0.12", features = [
  "prost",
] }
prost-build = "0.13"
anyhow = "1.0"
rustc_version = "0.4"
pbjson-build = "0.7"

[lib]
path = "src/lib.rs"
bench = false

[[bin]]
name = "agentproxy"
path = "src/main.rs"
bench = false

[dev-dependencies]
serde_json = "1.0"
tokio = "1.42"
wiremock = "0.6.3"
