[graph]
# Test supported features and targets
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "aarch64-unknown-linux-gnu" },
]
features = []

[advisories]
version = 2
ignore = [
    { id= "RUSTSEC-2024-0436", reason = "acceptable unmaintained package used in non-critical areas"}
]

[licenses]
version = 2
allow = ["Apache-2.0",
    "CC-BY-3.0",
    "ISC",
    "AFL-2.1",
    "AFL-3.0",
    "Artistic-1.0",
    "Artistic-2.0",
    "Apache-1.1",
    "BSD-1-Clause",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "0BSD",
    "FTL",
    "LPL-1.02",
    "MS-PL",
    "MIT",
    "NCSA",
    "OpenSSL",
    "PHP-3.0",
    "TCP-wrappers",
    "Unicode-3.0",
    "W3C",
    "Xnet",
    "Zlib",
    "Unicode-DFS-2016"
]
unused-allowed-license = "allow"
exceptions = [
    # https://github.com/rustls/webpki-roots/blob/main/LICENSE-APACHE
    { allow = ["CDLA-Permissive-2.0"], crate = "webpki-roots" },
]

# Deny cannot detect ring properly. Directly assign
[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[bans]
skip = [
    { crate = "regex-syntax", version = "0.6.29", reason = "acceptable duplicate" },
    { crate = "regex-automata", version = "0.1.10", reason = "acceptable duplicate" },
    { crate = "thiserror-impl", version = "1.0.69", reason = "acceptable duplicate" },
    { crate = "thiserror", version = "1.0.69", reason = "acceptable duplicate" },
    { crate = "bitflags" },
    { crate = "getrandom" },
    { crate = "itertools" },
    { crate = "nix" },
]

[sources]

allow-git = [
#    "https://github.com/janrueth/boring-rustls-provider",
]
