binds:
- port: 3000
  listeners:
  - routes:
    - policies:
        backendTLS: {}
        urlRewrite:
          path:
            prefix: /
        cors:
          allowOrigins:
          - "*"
          allowHeaders:
          - "*"
      matches:
      - path:
          pathPrefix: /atlassian
      backends:
      - mcp:
          name: atlassian
          targets:
          - name: mcp-atlassian
            mcp:
              host: mcp.context7.com
              port: 443
              path: /mcp