binds:
- port: 3000
  listeners:
  - routes:
    - backends:
      - ai:
          name: openai
          provider:
            openAI:
              model: gpt-4o-mini
      policies:
        ai:
          promptGuard:
            request:
              regex:
                action:
                  reject:
                    response:
                      status: 400
                      headers:
                        set:
                          content-type: "application/json"
                      body: |
                        {
                          "error": {
                            "message": "Request rejected: Content contains sensitive information",
                            "type": "invalid_request_error",
                            "code": "content_policy_violation"
                          }
                        }
                rules:
                - pattern: SSN
                  name: SSN
                - pattern: Social Security
                  name: Social Security
            response:
              regex:
                action:
                  reject:
                    response:
                      status: 400
                      headers:
                        set:
                          content-type: "application/json"
                      body: |
                        {
                          "error": {
                            "message": "Response blocked: Contains sensitive information",
                            "type": "invalid_request_error",
                            "code": "pii_detected"
                          }
                        }
                rules:
                - builtin: email