# Deployment Manifest for the MCP Proxy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentgateway
  labels:
    app: agentgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agentgateway
  template:
    metadata:
      labels:
        app: agentgateway
    spec:
      containers:
        - name: agentgateway
          image: ghcr.io/agentgateway/agentgateway:latest
          args:
            - -f
            - /etc/agentgateway/config.json
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: agentgateway-config
              mountPath: /etc/agentgateway/config.json
              subPath: config.json
      volumes:
        - name: agentgateway-config
          configMap:
            name: agentgateway-config
---
apiVersion: v1
kind: Service
metadata:
  name: agentgateway
spec:
  selector:
    app: agentgateway
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
# Deployment Manifest for the MCP Proxy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: everything
  labels:
    app: everything
spec:
  replicas: 1
  selector:
    matchLabels:
      app: everything
  template:
    metadata:
      labels:
        app: everything
    spec:
      containers:
        - name: everything
          image: ghcr.io/agentgateway/agentgateway:latest-ext
          args:
            - -f
            - /etc/agentgateway/config.json
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: everything-config
              mountPath: /etc/agentgateway/config.json
              subPath: config.json
      volumes:
        - name: everything-config
          configMap:
            name: everything-config
---
apiVersion: v1
kind: Service
metadata:
  name: everything
spec:
  selector:
    app: everything
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: everything-config
data:
  config.json: |
    {
      "type": "static",
      "listeners": [
        {
          "name": "sse",
          "protocol": "MCP",        
          "sse": {
            "address": "[::]",
            "port": 3000
          }
        }
      ],
      "targets": {
        "mcp": [
          {
            "name": "everything",
            "stdio": {
            "cmd": "npx",
            "args": [
                "@modelcontextprotocol/server-everything"
              ]
            }
          }
        ]
      }
    }

