export const routes = [
	['cel', '/cel', 'CEL Playground'],
	['llm-analytics', '/llm/analytics', 'Analytics'],
	['llm-client-setup', '/llm/client-setup', 'Client Setup'],
	['llm-costs', '/llm/costs', 'LLM Costs'],
	['llm-get-started', '/llm/get-started', 'Enable LLM', 'unconfigured'],
	['llm-guardrails', '/llm/guardrails', 'LLM Guardrails'],
	['llm-keys', '/llm/keys', 'Virtual API Keys'],
	['llm-logs', '/llm/logs', 'Logs'],
	['llm-models', '/llm/models', 'LLM Models'],
	['llm-playground', '/llm/playground', 'LLM Playground'],
	['llm-policies', '/llm/policies', 'LLM Policies'],
	['llm-providers', '/llm/providers', 'LLM Providers'],
	['mcp-get-started', '/mcp/get-started', 'Enable MCP', 'unconfigured'],
	['mcp-playground', '/mcp/playground', 'MCP Playground'],
	['mcp-policies', '/mcp/policies', 'MCP Policies'],
	['mcp-servers', '/mcp/servers', 'MCP Servers'],
	['overview', '/', 'Gateway Overview'],
	['raw-config', '/raw-config', 'Raw Configuration'],
	['settings', '/settings', 'UI Settings'],
	['traffic-gateways', '/traffic/gateways', 'Traffic Gateways'],
	['traffic-get-started', '/traffic/get-started', 'Enable Traffic', 'unconfigured'],
	['traffic-listeners', '/traffic/listeners', 'Traffic Listeners'],
	['traffic-policies', '/traffic/policies', 'Policies', 'xds'],
	['traffic-routes', '/traffic/routes', 'Traffic Routes']
] as const;
