[package]
name = "a2a-sdk"
version = "0.6.0"
edition = "2024"
description = "Unofficial Google A2A SDK"
license = "MIT"

[dependencies]
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
