apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: backend-mtls-files
spec:
  targetRefs:
  - group: agentgateway.dev
    kind: AgentgatewayBackend
    name: my-backend
  backend:
    tls:
      sni: api.example.internal
      mtlsCertificateRef:
      - kind: File
        file:
          cert: /var/run/certs/tls.crt
          key: /var/run/certs/tls.key
          root: /var/run/certs/ca.crt
