[alias]
xtask = "run --package xtask --"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "--cfg", "tokio_unstable"
]

[target.aarch64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "--cfg", "tokio_unstable"
]

[target.aarch64-apple-darwin]
rustflags = ["--cfg", "tokio_unstable"]

[target.x86_64-apple-darwin]
rustflags = ["--cfg", "tokio_unstable"]

[target.x86_64-pc-windows-msvc]
rustflags = ["--cfg", "tokio_unstable"]
