# yaml-language-server: $schema=https://agentgateway.dev/schema/config
llm:
  port: 3000
  models:
  - name: spark-x2.5
    provider: openAI
    params:
      model: spark-x2.5
      apiKey: $ASTRON_API_KEY
      baseUrl: https://maas-token-api.cn-huabei-1.xf-yun.com/v2
